spring.application.name=sanbong

# 1. Thông tin kết nối SQL Server
# (QuanLySanBong là tên database bạn đã tạo trong script)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=QuanLySanBong;encrypt=true;trustServerCertificate=true;

# Bạn nhớ thay username và password bằng tài khoản SQL Server của bạn nhé
spring.datasource.username=sa
spring.datasource.password=123

# 2. Cấu hình JPA / Hibernate cho SQL Server
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
sepay.api-key=UIXFNXJ06ISYJJQPZ78TEUJBTBIF8XMMEVRSNYW7OAQ6POAYUDNDRP1HR2IEG3FA