<template>
<div><h1 class="dashboard__page-title">Quản lý Voucher</h1><p class="dashboard__page-desc">Tạo ưu đãi theo hạng khách hàng và theo dõi lượt sử dụng.</p>
<div class="toolbar"><input v-model="tuKhoa" class="search-box" placeholder="Tìm mã hoặc tên voucher..."><select v-model="locDoiTuong" class="filter-box"><option value="">Tất cả hạng</option><option value="ALL">Tất cả</option><option value="NEW_USER">Khách mới</option><option value="SILVER">Silver</option><option value="GOLD">Gold</option><option value="DIAMOND">Diamond</option></select><button class="btn-add" @click="moThem">+ Thêm voucher</button></div>
<div class="card"><table><thead><tr><th>Mã</th><th>Tên</th><th>Giảm</th><th>Đối tượng</th><th>Đã dùng</th><th>Thời gian</th><th>Trạng thái</th><th></th></tr></thead><tbody><tr v-for="v in dsLoc" :key="v.id"><td><b>{{v.ma}}</b></td><td>{{v.ten}}</td><td>{{v.loaiGiam==='PHAN_TRAM'?v.giaTriGiam+'%':format(v.giaTriGiam)+'đ'}}</td><td><span class="badge">{{nhanHang(v.doiTuongKhachHang)}}</span></td><td>{{v.daSuDung}} / {{v.soLuong}}</td><td>{{date(v.ngayBatDau)}} → {{date(v.ngayKetThuc)}}</td><td><span :class="['status',v.trangThai]">{{v.trangThai}}</span></td><td class="actions"><button @click="moSua(v)">Sửa</button><button class="danger" @click="xoa(v)">Xóa</button></td></tr><tr v-if="!dsLoc.length"><td colspan="8" class="empty">Chưa có voucher.</td></tr></tbody></table></div>
<div v-if="hienForm" class="overlay"><div class="modal"><h2>{{dangSua?'Sửa voucher':'Thêm voucher'}}</h2><div class="grid"><label>Mã<input v-model="form.ma"></label><label>Tên<input v-model="form.ten"></label><label>Loại giảm<select v-model="form.loaiGiam"><option value="CO_DINH">Số tiền</option><option value="PHAN_TRAM">Phần trăm</option></select></label><label>Giá trị<input v-model.number="form.giaTriGiam" type="number"></label><label>Giảm tối đa<input v-model.number="form.giamToiDa" type="number"></label><label>Đơn tối thiểu<input v-model.number="form.donToiThieu" type="number"></label><label>Đối tượng<select v-model="form.doiTuongKhachHang"><option value="ALL">Tất cả</option><option value="NEW_USER">Khách mới</option><option value="SILVER">Silver</option><option value="GOLD">Gold</option><option value="DIAMOND">Diamond</option></select></label><label>Số lượng<input v-model.number="form.soLuong" type="number"></label><label>Giới hạn / khách<input v-model.number="form.gioiHanMoiKhach" type="number"></label><label>Bắt đầu<input v-model="form.ngayBatDau" type="datetime-local"></label><label>Kết thúc<input v-model="form.ngayKetThuc" type="datetime-local"></label><label>Trạng thái<select v-model="form.trangThai"><option value="HOAT_DONG">Hoạt động</option><option value="TAM_DUNG">Tạm dừng</option><option value="HET_HAN">Hết hạn</option></select></label></div><label class="full">Mô tả<textarea v-model="form.moTa"></textarea></label><p v-if="loi" class="error">{{loi}}</p><div class="modal-actions"><button class="btn-ghost" @click="hienForm=false">Hủy</button><button class="btn-primary" @click="luu">Lưu voucher</button></div></div></div>
</div></template>
<script setup>
import {ref,computed,onMounted} from 'vue';import voucherService from '../../services/voucherService'
const ds=ref([]),tuKhoa=ref(''),locDoiTuong=ref(''),hienForm=ref(false),dangSua=ref(false),loi=ref(''),idSua=ref(null)
const empty=()=>({ma:'',ten:'',moTa:'',loaiGiam:'CO_DINH',giaTriGiam:50000,giamToiDa:null,donToiThieu:null,doiTuongKhachHang:'ALL',soLuong:100,gioiHanMoiKhach:1,ngayBatDau:toLocal(new Date()),ngayKetThuc:toLocal(new Date(Date.now()+30*86400000)),trangThai:'HOAT_DONG'})
const form=ref(empty())
function toLocal(d){const z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z.toISOString().slice(0,16)}
const dsLoc=computed(()=>ds.value.filter(v=>(!locDoiTuong.value||v.doiTuongKhachHang===locDoiTuong.value)&&(!tuKhoa.value||`${v.ma} ${v.ten}`.toLowerCase().includes(tuKhoa.value.toLowerCase()))))
function format(n){return Number(n||0).toLocaleString('vi-VN')} function date(x){return new Date(x).toLocaleDateString('vi-VN')} function nhanHang(x){return {ALL:'Tất cả',NEW_USER:'Khách mới',SILVER:'Silver',GOLD:'Gold',DIAMOND:'Diamond'}[x]||x}
async function tai(){try{ds.value=await voucherService.all()}catch(e){loi.value=e.message}} function moThem(){dangSua.value=false;idSua.value=null;form.value=empty();loi.value='';hienForm.value=true} function moSua(v){dangSua.value=true;idSua.value=v.id;form.value={...v,ngayBatDau:toLocal(new Date(v.ngayBatDau)),ngayKetThuc:toLocal(new Date(v.ngayKetThuc))};loi.value='';hienForm.value=true}
async function luu(){try{loi.value='';if(dangSua.value)await voucherService.edit(idSua.value,form.value);else await voucherService.add(form.value);hienForm.value=false;await tai()}catch(e){loi.value=e.message}} async function xoa(v){if(!confirm(`Xóa voucher ${v.ma}?`))return;try{await voucherService.remove(v.id);await tai()}catch(e){alert(e.message)}} onMounted(tai)
</script>
<style scoped>
.dashboard__page-title{font-size:24px;font-weight:700;color:#1e293b;margin:0 0 6px}.dashboard__page-desc{font-size:14px;color:#64748b;margin:0 0 28px}.toolbar{display:flex;gap:10px;margin-bottom:18px}.search-box,.filter-box{padding:10px 12px;border:1px solid #cbd5e1;border-radius:8px;background:#fff}.search-box{flex:1}.btn-add,.btn-primary{border:0;background:#16a34a;color:#fff;border-radius:8px;padding:10px 16px;font-weight:700;cursor:pointer}.card{background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:auto}table{width:100%;border-collapse:collapse;font-size:13px}th,td{padding:13px;border-bottom:1px solid #eef2f7;text-align:left;white-space:nowrap}th{background:#f8fafc;color:#475569}.badge{padding:4px 8px;border-radius:999px;background:#ecfdf5;color:#15803d}.status{padding:4px 8px;border-radius:999px;background:#f1f5f9}.HOAT_DONG{color:#15803d;background:#dcfce7}.TAM_DUNG{color:#b45309;background:#fef3c7}.HET_HAN{color:#b91c1c;background:#fee2e2}.actions{display:flex;gap:6px}.actions button,.btn-ghost{border:1px solid #cbd5e1;background:#fff;border-radius:7px;padding:6px 10px;cursor:pointer}.actions .danger{color:#dc2626}.empty{text-align:center;color:#94a3b8;padding:30px}.overlay{position:fixed;inset:0;background:rgba(15,23,42,.4);display:flex;align-items:center;justify-content:center;z-index:20}.modal{background:#fff;width:min(760px,92vw);max-height:90vh;overflow:auto;border-radius:14px;padding:24px}.modal h2{margin:0 0 18px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.grid label,.full{display:flex;flex-direction:column;gap:6px;font-size:13px;font-weight:600;color:#475569}.grid input,.grid select,.full textarea{padding:9px;border:1px solid #cbd5e1;border-radius:7px}.full{margin-top:14px}.full textarea{min-height:80px}.modal-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:18px}.error{color:#dc2626;font-size:13px}@media(max-width:700px){.grid{grid-template-columns:1fr}.toolbar{flex-wrap:wrap}.search-box{min-width:100%}}
</style>
