package com.dream.sanbong.service;
import com.dream.sanbong.dto.*; import com.dream.sanbong.entity.*; import com.dream.sanbong.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.math.*; import java.time.*; import java.util.*;
@Service public class VoucherServiceImpl implements VoucherService {
 private final VoucherRepository vr; private final SuDungVoucherRepository sr; private final NguoiDungRepository ur; private final DatSanRepository dr;
 public VoucherServiceImpl(VoucherRepository vr,SuDungVoucherRepository sr,NguoiDungRepository ur,DatSanRepository dr){this.vr=vr;this.sr=sr;this.ur=ur;this.dr=dr;}
 private VoucherPhanHoi map(Voucher v){return new VoucherPhanHoi(v.getId(),v.getMa(),v.getTen(),v.getMoTa(),v.getLoaiGiam(),v.getGiaTriGiam(),v.getGiamToiDa(),v.getDonToiThieu(),v.getDoiTuongKhachHang(),v.getSoLuong(),v.getDaSuDung(),v.getGioiHanMoiKhach(),v.getNgayBatDau(),v.getNgayKetThuc(),v.getTrangThai());}
 public List<VoucherPhanHoi> layTatCa(){return vr.findAllByOrderByNgayBatDauDesc().stream().map(this::map).toList();}
 public List<VoucherThongBaoPhanHoi> layVoucherDangHoatDong(){
  LocalDateTime now=LocalDateTime.now();
  return vr.findVoucherDangHoatDong("HOAT_DONG",now).stream()
      .map(v -> VoucherThongBaoPhanHoi.builder()
          .id(v.getId()).ma(v.getMa()).ten(v.getTen()).moTa(v.getMoTa())
          .loaiGiam(v.getLoaiGiam()).giaTriGiam(v.getGiaTriGiam()).giamToiDa(v.getGiamToiDa())
          .donToiThieu(v.getDonToiThieu()).doiTuongKhachHang(v.getDoiTuongKhachHang())
          .ngayKetThuc(v.getNgayKetThuc()).build())
      .toList();
 }
 private void validate(VoucherYeuCau y){if(y.getMa()==null||y.getMa().isBlank())throw new RuntimeException("Mã voucher không được để trống!"); if(y.getGiaTriGiam()==null||y.getGiaTriGiam().compareTo(BigDecimal.ZERO)<=0)throw new RuntimeException("Giá trị giảm phải lớn hơn 0!"); if("PHAN_TRAM".equals(y.getLoaiGiam())&&y.getGiaTriGiam().compareTo(BigDecimal.valueOf(100))>0)throw new RuntimeException("Giảm phần trăm không được vượt quá 100%!"); if(y.getNgayBatDau()==null||y.getNgayKetThuc()==null||!y.getNgayKetThuc().isAfter(y.getNgayBatDau()))throw new RuntimeException("Thời gian voucher không hợp lệ!"); if(y.getSoLuong()==null||y.getSoLuong()<=0)throw new RuntimeException("Số lượng phải lớn hơn 0!");}
 @Transactional public VoucherPhanHoi them(VoucherYeuCau y){validate(y); if(vr.findByMaIgnoreCase(y.getMa()).isPresent())throw new RuntimeException("Mã voucher đã tồn tại!"); Voucher v=Voucher.builder().ma(y.getMa().trim().toUpperCase()).ten(y.getTen()).moTa(y.getMoTa()).loaiGiam(y.getLoaiGiam()).giaTriGiam(y.getGiaTriGiam()).giamToiDa(y.getGiamToiDa()).donToiThieu(y.getDonToiThieu()).doiTuongKhachHang(y.getDoiTuongKhachHang()).soLuong(y.getSoLuong()).daSuDung(0).gioiHanMoiKhach(y.getGioiHanMoiKhach()==null?1:y.getGioiHanMoiKhach()).ngayBatDau(y.getNgayBatDau()).ngayKetThuc(y.getNgayKetThuc()).trangThai(y.getTrangThai()==null?"HOAT_DONG":y.getTrangThai()).build(); return map(vr.save(v));}
 @Transactional public VoucherPhanHoi sua(UUID id,VoucherYeuCau y){validate(y); Voucher v=vr.findById(id).orElseThrow(()->new RuntimeException("Không tìm thấy voucher!")); vr.findByMaIgnoreCase(y.getMa()).filter(x->!x.getId().equals(id)).ifPresent(x->{throw new RuntimeException("Mã voucher đã tồn tại!");}); v.setMa(y.getMa().trim().toUpperCase());v.setTen(y.getTen());v.setMoTa(y.getMoTa());v.setLoaiGiam(y.getLoaiGiam());v.setGiaTriGiam(y.getGiaTriGiam());v.setGiamToiDa(y.getGiamToiDa());v.setDonToiThieu(y.getDonToiThieu());v.setDoiTuongKhachHang(y.getDoiTuongKhachHang());v.setSoLuong(Math.max(y.getSoLuong(),v.getDaSuDung()));v.setGioiHanMoiKhach(y.getGioiHanMoiKhach()==null?1:y.getGioiHanMoiKhach());v.setNgayBatDau(y.getNgayBatDau());v.setNgayKetThuc(y.getNgayKetThuc());v.setTrangThai(y.getTrangThai());return map(vr.save(v));}
 @Transactional public void xoa(UUID id){Voucher v=vr.findById(id).orElseThrow(()->new RuntimeException("Không tìm thấy voucher!")); if(v.getDaSuDung()>0)throw new RuntimeException("Voucher đã được sử dụng, không thể xoá. Hãy chuyển trạng thái TẠM DỪNG!"); vr.delete(v);}
 private Object[] hang(String email){NguoiDung u=ur.findByEmail(email).orElseThrow(()->new RuntimeException("Không tìm thấy tài khoản!")); long n=dr.demSoLuotDatVoucher30Ngay(u.getId()); if(n>=10)return new Object[]{"DIAMOND",10,n}; if(n>=6)return new Object[]{"GOLD",6,n}; if(n>=3)return new Object[]{"SILVER",3,n}; return new Object[]{"MEMBER",0,n};}
 private BigDecimal tinh(Voucher v,BigDecimal don){if(v.getDonToiThieu()!=null&&don.compareTo(v.getDonToiThieu())<0)throw new RuntimeException("Đơn tối thiểu để dùng mã là "+v.getDonToiThieu().setScale(0).toPlainString()+"đ."); BigDecimal g="PHAN_TRAM".equals(v.getLoaiGiam())?don.multiply(v.getGiaTriGiam()).divide(BigDecimal.valueOf(100),2,RoundingMode.HALF_UP):v.getGiaTriGiam(); if(v.getGiamToiDa()!=null&&g.compareTo(v.getGiamToiDa())>0)g=v.getGiamToiDa(); return g.min(don);}
 private void checkTarget(Voucher v,String hang,long soLuot){String target=v.getDoiTuongKhachHang(); boolean ok="ALL".equals(target)||("NEW_USER".equals(target)&&soLuot==0)||target.equals(hang); if(!ok)throw new RuntimeException("Mã này dành cho khách Hạng "+target+". Hạng hiện tại của bạn là "+hang+".");}
 @Transactional public VoucherKiemTraPhanHoi kiemTra(String ma,BigDecimal donHang,String email){if(donHang==null||donHang.signum()<=0)throw new RuntimeException("Giá trị đơn hàng không hợp lệ!"); Voucher v=vr.findByMaIgnoreCase(ma==null?"":ma.trim()).orElseThrow(()->new RuntimeException("Mã voucher không tồn tại!")); LocalDateTime now=LocalDateTime.now(); if(!"HOAT_DONG".equals(v.getTrangThai())||now.isBefore(v.getNgayBatDau())||now.isAfter(v.getNgayKetThuc()))throw new RuntimeException("Voucher chưa hoạt động hoặc đã hết hạn!"); if(v.getDaSuDung()>=v.getSoLuong())throw new RuntimeException("Voucher đã hết lượt sử dụng!"); Object[] h=hang(email); String hang=(String)h[0]; checkTarget(v,hang,(Long)h[2]); long used=sr.countByVoucherIdAndNguoiDungId(v.getId(),ur.findByEmail(email).get().getId()); if(used>=v.getGioiHanMoiKhach())throw new RuntimeException("Bạn đã sử dụng voucher này đủ số lần cho phép!"); BigDecimal g=tinh(v,donHang); return VoucherKiemTraPhanHoi.builder().hopLe(true).ma(v.getMa()).ten(v.getTen()).thongBao("Áp dụng mã "+v.getMa()+" thành công!").hangKhachHang(hang).soLuotDat((Long)h[2]).nguongHang((Integer)h[1]).soTienGiam(g).donHangSauGiam(donHang.subtract(g)).build();}
 @Transactional public void apDungChoDatSan(String ma,BigDecimal tongTien,String email,DatSan datSan){if(ma==null||ma.isBlank())return; VoucherKiemTraPhanHoi k=kiemTra(ma,tongTien,email); Voucher v=vr.findByMaIgnoreCase(k.getMa()).get(); NguoiDung u=ur.findByEmail(email).get(); v.setDaSuDung(v.getDaSuDung()+1); vr.save(v); sr.save(SuDungVoucher.builder().voucher(v).nguoiDung(u).datSan(datSan).soTienGiam(k.getSoTienGiam()).build()); datSan.setVoucherId(v.getId());datSan.setTienGiamVoucher(k.getSoTienGiam()); }
 @Transactional public void hoanVoucher(UUID datSanId){sr.findByDatSanId(datSanId).ifPresent(s->{Voucher v=s.getVoucher();v.setDaSuDung(Math.max(0,v.getDaSuDung()-1));vr.save(v);sr.delete(s);});}
}
